myapp/models.py
#models 
from myapp import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
#allows to set up isAuthenticate etc 
from flask_login import UserMixin
from datetime import datetime

#login management 
# allows us to use this in templates for isUser stuff 
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

#going to use this in our login view 
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def __repr__(self):
        return f"Username {self.username}"

myapp/users/forms.py
#users/forms.py 

# forms related imports
from ast import Pass
from click import password_option
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed # update png or jpeg file to display profile image

# Users related imports 
from flask_login import current_user
from myapp.models import User 

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords must match!')])
    # we make sure password is equal to pass confirm - so 
    pass_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')
    
    #when someone is registering - if the email exists then we want to raise a validation error
    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')
    
    #same as above but checking username
    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')
    

class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Update')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')
    
    #same as above but checking username
    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')

myapp/__init__.py
# myapp/__init__.py 

from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
import os
from os import environ, path 
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

############################
###### DATABASE SETUP ######
############################


# set up connection to db
app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql:///pillow"
# app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
db.init_app(app)
Migrate(app, db)


#############################

############ LOGIN CONFIGS ##############

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'





# Registering Blueprints - 

from myapp.core.views import core 
app.register_blueprint(core)

#linking the 404 and 403 error pages into the app 
from myapp.error_pages.handlers import error_pages
app.register_blueprint(error_pages)


#linking users views Blueprint
from myapp.users.views import users
app.register_blueprint(users)

myapp/core/views.py
# core/views.py 

from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}
   
<div class="jumbotron">
    <div align="center">
        <h1>Welcome to the page for {{current_user.username}}</h1>
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            {{form.username.label(class='form-group')}} 
            {{form.username(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.email.label(class='form-group')}} 
            {{form.email(class='form-control')}}
        </div>
      
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
       
       
    </form>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Party!</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-link">
            <a href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('core.info')}}">About</a>
        </li>

        {% if current_user.is_authenticated %}
        <li class="nav-link">
            <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.account')}}">Account</a>
        </li>
        {% else %}
        <li class="nav-link">
            <a href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.register')}}">Register</a>
        </li>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Party!</h1>
    </div>
   
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Info about our party!!</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit veniam nihil nostrum excepturi nulla error quaerat reprehenderit, iste ad accusamus amet nesciunt, provident laborum, voluptas molestias unde non est perferendis?</p>
    </div>
   
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
   
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}}

</form>
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
   
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    {{form.submit()}}
</form>
{% endblock %}